export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "refactor",
        "test",
        "docs",
        "chore",
        "build",
        "ci",
        "perf",
        "revert",
      ],
    ],
    "scope-enum": [
      2,
      "always",
      [
        "repo",
        "api",
        "web",
        "mcp",
        "shared",
        "docker",
        "ci",
        "docs",
        "db",
        "providers",
        "apps",
        "keywords",
        "rankings",
        "scoring",
        "competitors",
        "analytics",
        "jobs",
        "audit",
        "metadata",
        "changes",
        "alerts",
        "auth",
        "actions",
        "deps",
        "deps-dev",
      ],
    ],
    "scope-empty": [2, "never"],
    "subject-case": [
      2,
      "never",
      ["sentence-case", "start-case", "pascal-case", "upper-case"],
    ],
    "subject-full-stop": [2, "never", "."],
    "subject-max-length": [2, "always", 72],
  },
};
