export const APP_STORE_LOCALIZATIONS = {
  ar: 'Arabic',
  bn: 'Bangla',
  ca: 'Catalan',
  'zh-Hans': 'Chinese (Simplified)',
  'zh-Hant': 'Chinese (Traditional)',
  hr: 'Croatian',
  cs: 'Czech',
  da: 'Danish',
  nl: 'Dutch',
  'en-AU': 'English (Australia)',
  'en-CA': 'English (Canada)',
  'en-GB': 'English (U.K.)',
  'en-US': 'English (U.S.)',
  fi: 'Finnish',
  fr: 'French',
  'fr-CA': 'French (Canada)',
  de: 'German',
  el: 'Greek',
  gu: 'Gujarati',
  he: 'Hebrew',
  hi: 'Hindi',
  hu: 'Hungarian',
  id: 'Indonesian',
  it: 'Italian',
  ja: 'Japanese',
  kn: 'Kannada',
  ko: 'Korean',
  ms: 'Malay',
  ml: 'Malayalam',
  mr: 'Marathi',
  no: 'Norwegian',
  or: 'Odia',
  pl: 'Polish',
  'pt-BR': 'Portuguese (Brazil)',
  'pt-PT': 'Portuguese (Portugal)',
  pa: 'Punjabi',
  ro: 'Romanian',
  ru: 'Russian',
  sk: 'Slovak',
  sl: 'Slovenian',
  'es-MX': 'Spanish (Mexico)',
  'es-ES': 'Spanish (Spain)',
  sv: 'Swedish',
  ta: 'Tamil',
  te: 'Telugu',
  th: 'Thai',
  tr: 'Turkish',
  uk: 'Ukrainian',
  ur: 'Urdu',
  vi: 'Vietnamese',
} as const;

export type AppStoreLocalization = keyof typeof APP_STORE_LOCALIZATIONS;

export const isAppStoreLocalization = (
  value: unknown,
): value is AppStoreLocalization =>
  typeof value === 'string' && Object.hasOwn(APP_STORE_LOCALIZATIONS, value);

export const APP_STORE_LOCALIZATION_IDS: readonly AppStoreLocalization[] =
  Object.keys(APP_STORE_LOCALIZATIONS).filter(isAppStoreLocalization);

export interface StorefrontLocalizations {
  readonly primary: AppStoreLocalization;
  readonly additional: readonly AppStoreLocalization[];
}

export const APP_STORE_STOREFRONT_LOCALIZATIONS: Readonly<
  Record<string, StorefrontLocalizations>
> = Object.freeze({
  ae: { primary: 'en-GB', additional: ['ar'] },
  af: { primary: 'en-GB', additional: [] },
  ag: { primary: 'en-GB', additional: [] },
  ai: { primary: 'en-GB', additional: [] },
  al: { primary: 'en-GB', additional: [] },
  am: { primary: 'en-GB', additional: [] },
  ao: { primary: 'en-GB', additional: [] },
  ar: { primary: 'es-MX', additional: ['en-GB'] },
  at: { primary: 'de', additional: ['en-GB'] },
  au: { primary: 'en-AU', additional: ['en-GB'] },
  az: { primary: 'en-GB', additional: [] },
  ba: { primary: 'en-GB', additional: ['hr'] },
  bb: { primary: 'en-GB', additional: [] },
  be: { primary: 'en-GB', additional: ['nl', 'fr'] },
  bf: { primary: 'en-GB', additional: ['fr'] },
  bg: { primary: 'en-GB', additional: [] },
  bh: { primary: 'en-GB', additional: ['ar'] },
  bj: { primary: 'en-GB', additional: ['fr'] },
  bm: { primary: 'en-GB', additional: [] },
  bn: { primary: 'en-GB', additional: [] },
  bo: { primary: 'es-MX', additional: ['en-GB'] },
  br: { primary: 'pt-BR', additional: ['en-GB'] },
  bs: { primary: 'en-GB', additional: [] },
  bt: { primary: 'en-GB', additional: [] },
  bw: { primary: 'en-GB', additional: [] },
  by: { primary: 'en-GB', additional: [] },
  bz: { primary: 'en-GB', additional: ['es-MX'] },
  ca: { primary: 'en-CA', additional: ['fr-CA'] },
  cd: { primary: 'en-GB', additional: ['fr'] },
  cg: { primary: 'en-GB', additional: ['fr'] },
  ch: { primary: 'de', additional: ['en-GB', 'fr', 'it'] },
  ci: { primary: 'fr', additional: ['en-GB'] },
  cl: { primary: 'es-MX', additional: ['en-GB'] },
  cm: { primary: 'fr', additional: ['en-GB'] },
  cn: { primary: 'zh-Hans', additional: ['en-GB'] },
  co: { primary: 'es-MX', additional: ['en-GB'] },
  cr: { primary: 'es-MX', additional: ['en-GB'] },
  cv: { primary: 'en-GB', additional: [] },
  cy: { primary: 'en-GB', additional: ['el', 'tr'] },
  cz: { primary: 'en-GB', additional: ['cs'] },
  de: { primary: 'de', additional: ['en-GB'] },
  dk: { primary: 'en-GB', additional: ['da'] },
  dm: { primary: 'en-GB', additional: [] },
  do: { primary: 'es-MX', additional: ['en-GB'] },
  dz: { primary: 'en-GB', additional: ['ar', 'fr'] },
  ec: { primary: 'es-MX', additional: ['en-GB'] },
  ee: { primary: 'en-GB', additional: [] },
  eg: { primary: 'en-GB', additional: ['ar', 'fr'] },
  es: { primary: 'es-ES', additional: ['ca', 'en-GB'] },
  fi: { primary: 'en-GB', additional: ['fi'] },
  fj: { primary: 'en-GB', additional: [] },
  fm: { primary: 'en-GB', additional: [] },
  fr: { primary: 'fr', additional: ['en-GB'] },
  ga: { primary: 'fr', additional: ['en-GB'] },
  gb: { primary: 'en-GB', additional: [] },
  gd: { primary: 'en-GB', additional: [] },
  ge: { primary: 'en-GB', additional: [] },
  gh: { primary: 'en-GB', additional: [] },
  gm: { primary: 'en-GB', additional: [] },
  gr: { primary: 'en-GB', additional: ['el'] },
  gt: { primary: 'es-MX', additional: ['en-GB'] },
  gw: { primary: 'en-GB', additional: ['fr'] },
  gy: { primary: 'en-GB', additional: ['fr'] },
  hk: { primary: 'zh-Hant', additional: ['en-GB'] },
  hn: { primary: 'es-MX', additional: ['en-GB'] },
  hr: { primary: 'en-GB', additional: ['hr'] },
  hu: { primary: 'en-GB', additional: ['hu'] },
  id: { primary: 'en-GB', additional: ['id'] },
  ie: { primary: 'en-GB', additional: [] },
  il: { primary: 'en-GB', additional: ['he'] },
  in: {
    primary: 'en-GB',
    additional: [
      'bn',
      'gu',
      'hi',
      'kn',
      'ml',
      'mr',
      'or',
      'pa',
      'ta',
      'te',
      'ur',
    ],
  },
  iq: { primary: 'en-GB', additional: ['ar'] },
  is: { primary: 'en-GB', additional: [] },
  it: { primary: 'it', additional: ['en-GB'] },
  jm: { primary: 'en-GB', additional: [] },
  jo: { primary: 'en-GB', additional: ['ar'] },
  jp: { primary: 'ja', additional: ['en-US'] },
  ke: { primary: 'en-GB', additional: [] },
  kg: { primary: 'en-GB', additional: [] },
  kh: { primary: 'en-GB', additional: ['fr'] },
  kn: { primary: 'en-GB', additional: [] },
  kr: { primary: 'ko', additional: ['en-GB'] },
  kw: { primary: 'en-GB', additional: ['ar'] },
  ky: { primary: 'en-GB', additional: [] },
  kz: { primary: 'en-GB', additional: [] },
  la: { primary: 'en-GB', additional: ['fr'] },
  lb: { primary: 'en-GB', additional: ['ar', 'fr'] },
  lc: { primary: 'en-GB', additional: [] },
  lk: { primary: 'en-GB', additional: [] },
  lr: { primary: 'en-GB', additional: [] },
  lt: { primary: 'en-GB', additional: [] },
  lu: { primary: 'en-GB', additional: ['fr', 'de'] },
  lv: { primary: 'en-GB', additional: [] },
  ly: { primary: 'en-GB', additional: ['ar'] },
  ma: { primary: 'en-GB', additional: ['ar', 'fr'] },
  md: { primary: 'en-GB', additional: [] },
  me: { primary: 'en-GB', additional: ['hr'] },
  mg: { primary: 'en-GB', additional: ['fr'] },
  mk: { primary: 'en-GB', additional: [] },
  ml: { primary: 'en-GB', additional: ['fr'] },
  mm: { primary: 'en-GB', additional: [] },
  mn: { primary: 'en-GB', additional: [] },
  mo: { primary: 'zh-Hant', additional: ['en-GB'] },
  mr: { primary: 'en-GB', additional: ['ar', 'fr'] },
  ms: { primary: 'en-GB', additional: [] },
  mt: { primary: 'en-GB', additional: [] },
  mu: { primary: 'en-GB', additional: ['fr'] },
  mv: { primary: 'en-GB', additional: [] },
  mw: { primary: 'en-GB', additional: [] },
  mx: { primary: 'es-MX', additional: ['en-GB'] },
  my: { primary: 'en-GB', additional: ['ms'] },
  mz: { primary: 'en-GB', additional: [] },
  na: { primary: 'en-GB', additional: [] },
  ne: { primary: 'en-GB', additional: ['fr'] },
  ng: { primary: 'en-GB', additional: [] },
  ni: { primary: 'es-MX', additional: ['en-GB'] },
  nl: { primary: 'nl', additional: ['en-GB'] },
  no: { primary: 'en-GB', additional: ['no'] },
  np: { primary: 'en-GB', additional: [] },
  nr: { primary: 'en-GB', additional: [] },
  nz: { primary: 'en-AU', additional: ['en-GB'] },
  om: { primary: 'en-GB', additional: ['ar'] },
  pa: { primary: 'es-MX', additional: ['en-GB'] },
  pe: { primary: 'es-MX', additional: ['en-GB'] },
  pg: { primary: 'en-GB', additional: [] },
  ph: { primary: 'en-GB', additional: [] },
  pk: { primary: 'en-GB', additional: ['ur'] },
  pl: { primary: 'en-GB', additional: ['pl'] },
  pt: { primary: 'pt-PT', additional: ['en-GB'] },
  pw: { primary: 'en-GB', additional: [] },
  py: { primary: 'es-MX', additional: ['en-GB'] },
  qa: { primary: 'en-GB', additional: ['ar'] },
  ro: { primary: 'en-GB', additional: ['ro'] },
  rs: { primary: 'en-GB', additional: ['hr'] },
  ru: { primary: 'ru', additional: ['en-GB', 'uk'] },
  rw: { primary: 'en-GB', additional: ['fr'] },
  sa: { primary: 'en-GB', additional: ['ar'] },
  sb: { primary: 'en-GB', additional: [] },
  sc: { primary: 'en-GB', additional: ['fr'] },
  se: { primary: 'sv', additional: ['en-GB'] },
  sg: { primary: 'en-GB', additional: ['zh-Hans'] },
  si: { primary: 'en-GB', additional: ['sl'] },
  sk: { primary: 'en-GB', additional: ['sk'] },
  sl: { primary: 'en-GB', additional: [] },
  sn: { primary: 'en-GB', additional: ['fr'] },
  sr: { primary: 'en-GB', additional: ['nl'] },
  st: { primary: 'en-GB', additional: [] },
  sv: { primary: 'es-MX', additional: ['en-GB'] },
  sz: { primary: 'en-GB', additional: [] },
  tc: { primary: 'en-GB', additional: [] },
  td: { primary: 'en-GB', additional: ['fr'] },
  th: { primary: 'en-GB', additional: ['th'] },
  tj: { primary: 'en-GB', additional: [] },
  tm: { primary: 'en-GB', additional: [] },
  tn: { primary: 'en-GB', additional: ['ar', 'fr'] },
  to: { primary: 'en-GB', additional: [] },
  tr: { primary: 'en-GB', additional: ['tr'] },
  tt: { primary: 'en-GB', additional: ['fr'] },
  tw: { primary: 'zh-Hant', additional: ['en-GB'] },
  tz: { primary: 'en-GB', additional: [] },
  ua: { primary: 'en-GB', additional: ['ru', 'uk'] },
  ug: { primary: 'en-GB', additional: [] },
  us: {
    primary: 'en-US',
    additional: [
      'ar',
      'zh-Hans',
      'zh-Hant',
      'fr',
      'ko',
      'pt-BR',
      'ru',
      'es-MX',
      'vi',
    ],
  },
  uy: { primary: 'en-GB', additional: ['es-MX'] },
  uz: { primary: 'en-GB', additional: [] },
  vc: { primary: 'en-GB', additional: [] },
  ve: { primary: 'es-MX', additional: ['en-GB'] },
  vg: { primary: 'en-GB', additional: [] },
  vn: { primary: 'en-GB', additional: ['vi'] },
  vu: { primary: 'en-GB', additional: ['fr'] },
  xk: { primary: 'en-GB', additional: [] },
  ye: { primary: 'en-GB', additional: ['ar'] },
  za: { primary: 'en-GB', additional: [] },
  zm: { primary: 'en-GB', additional: [] },
  zw: { primary: 'en-GB', additional: [] },
});

export function storefrontLocalizations(
  country: string,
): StorefrontLocalizations | null {
  const key = country.toLowerCase();
  return Object.hasOwn(APP_STORE_STOREFRONT_LOCALIZATIONS, key)
    ? APP_STORE_STOREFRONT_LOCALIZATIONS[key]
    : null;
}
