export const STOREFRONT_LANGUAGES: Readonly<Record<string, string>> =
  Object.freeze({
    us: 'en',
    gb: 'en',
    au: 'en',
    ca: 'en',
    ie: 'en',
    nz: 'en',
    in: 'en',
    ph: 'en',
    sg: 'en',
    za: 'en',
    de: 'de',
    at: 'de',
    ch: 'de',
    fr: 'fr',
    es: 'es',
    mx: 'es',
    ar: 'es',
    co: 'es',
    cl: 'es',
    it: 'it',
    pt: 'pt',
    br: 'pt',
    nl: 'nl',
    pl: 'pl',
    se: 'sv',
    no: 'no',
    dk: 'da',
    fi: 'fi',
    jp: 'ja',
    kr: 'ko',
    tw: 'zh',
    hk: 'zh',
    ru: 'ru',
    tr: 'tr',
    ua: 'uk',
    cz: 'cs',
    sk: 'sk',
    hu: 'hu',
    ro: 'ro',
    gr: 'el',
    il: 'he',
    sa: 'ar',
    ae: 'ar',
    eg: 'ar',
    th: 'th',
    vn: 'vi',
    id: 'id',
    my: 'ms',
  });

export function storefrontLanguage(country: string): string | null {
  const key = country.toLowerCase();
  return Object.hasOwn(STOREFRONT_LANGUAGES, key)
    ? STOREFRONT_LANGUAGES[key]
    : null;
}
