CREATE OR REPLACE FUNCTION app_enter_cross_tenant() RETURNS void
  LANGUAGE plpgsql
  AS $$
BEGIN
  PERFORM set_config('app.bypass_tenancy', 'on', true);
  SET LOCAL ROLE asobeast_app;
END $$;

ALTER TABLE "ActionItem" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AlertDelivery" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AlertEvent" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ApiToken" FORCE ROW LEVEL SECURITY;
ALTER TABLE "App" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AppGroup" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AppSnapshot" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AuditInsight" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AuditScore" FORCE ROW LEVEL SECURITY;
ALTER TABLE "CategoryRank" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ChangeEvent" FORCE ROW LEVEL SECURITY;
ALTER TABLE "EmailAlert" FORCE ROW LEVEL SECURITY;
ALTER TABLE "KeywordRanking" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Review" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SuggestProbe" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TrackedKeyword" FORCE ROW LEVEL SECURITY;
ALTER TABLE "User" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Webhook" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Workspace" FORCE ROW LEVEL SECURITY;
